version: '3.4'

services:
  cachedb:
    image: redis:alpine

  guitarshop.backend.api:
    image: ${DOCKER_REGISTRY-}guitarshopbackendapi
    build:
      context: .
      dockerfile: src/Api/GuitarShop.Backend.Api/Dockerfile
